@startuml
skinparam componentStyle uml2

node "Сервер Базы Данных" {
  package "База данных" {
    [Database]
  }
}

node "Сервер Текстового Редактора" {
  package "Текстовый редактор" {
    [TextEditor]
    [ImageLoader]
  }
}

node "Клиентская машина" {
  [Пользовательский интерфейс]
}

[Пользовательский интерфейс] --> TextEditor
TextEditor --> ImageLoader
ImageLoader --> Database
@enduml
