@startuml
actor Пользователь
participant TextEditor
participant Документ

Пользователь -> TextEditor: Открыть документ
TextEditor -> Документ: Инициализировать документ
Документ --> TextEditor: Вернуть документ
TextEditor --> Пользователь: Предложить редактировать документ
Пользователь -> TextEditor: Найти текст
TextEditor -> Документ: Найти текст
Документ --> TextEditor: Вернуть найденный текст
TextEditor --> Пользователь: Покажать найденный текст
@enduml
