@startuml
actor Гражданин
actor Орган_государственной_власти
actor Некоммерческая_организация
actor Федеральное_агентство

usecase Подача_заявки
usecase Обработка_заявки
usecase Предоставление_услуги
usecase Координация

Гражданин --> Подача_заявки : Отправляет заявку
Некоммерческая_организация --> Подача_заявки : Отправляет заявку
Подача_заявки --> Обработка_заявки : Переходит к обработке
Обработка_заявки --> Предоставление_услуги : После анализа заявки
Предоставление_услуги --> Координация : После предоставления услуги
Федеральное_агентство --> Координация : Мониторинг и координация

@enduml
