@startuml
left to right direction
actor Пользователь
rectangle "Система текстового редактора" {
  Пользователь -- (Создание нового документа)
  Пользователь -- (Открытие существующего документа)
  Пользователь -- (Редактирование текста)
  Пользователь -- (Сохранение изменений)
  Пользователь -- (Закрытие документа)
  Пользователь -- (Печать документа)
  Пользователь -- (Поиск текста)
  Пользователь -- (Вставка текста)
  Пользователь -- (Удаление текста)
  Пользователь -- (Форматирование текста)
}
@enduml
