@startuml
package "com.example.texteditor.document" {
  class Документ {
    +открыть()
    +сохранить()
    +закрыть()
    +печать()
    +найтиТекст()
    +вставитьТекст()
    +удалитьТекст()
    +форматироватьТекст()
  }
}

package "com.example.texteditor.service" {
  class ServicePrint {
    +print(Документ doc)
  }
}

class TextEditor {
  -документ : Документ
  +редактировать()
  +создатьНовыйДокумент()
  +открытьСуществующийДокумент()
  +сохранитьИзменения()
  +закрытьДокумент()
  +печатьДокумента()
  +поискТекста()
  +вставкаТекста()
  +удалениеТекста()
  +форматированиеТекста()
}

TextEditor "1" *-- "многие" Документ : использует >
TextEditor "1" *-- "один" ServicePrint : агрегирует >
@enduml
